### PR TITLE
[API] add link to api call names in description 

### PR DESCRIPTION
**Pull request by utkarsha-deriv**
This PR links the api call names inside the description of a given call. Upon clicking a particular keyword which is basically an api call name, the page re-renders and loads the description page of that api call name. 

Screenshot 2023-12-11 at 5 49 48 PM

### CODE REVIEW

**Review by review-deriv — COMMENTED** [review]
PR description is too short. You can use this format:

```
# Description
This is a summary of the changes. This should describe why do we need this change.
Whys and Hows come here.

# Cards
* https://clickup.com/12345
* https://clickup.com/12346

```

**Review by review-deriv — COMMENTED** [review]
PR description is too short. You can use this format:

```
# Description
This is a summary of the changes. This should describe why do we need this change.
Whys and Hows come here.

# Cards
* https://clickup.com/12345
* https://clickup.com/12346

```

**Review by review-deriv — COMMENTED** [review]
PR description is too short. You can use this format:

```
# Description
This is a summary of the changes. This should describe why do we need this change.
Whys and Hows come here.

# Cards
* https://clickup.com/12345
* https://clickup.com/12346

```

**Review by review-deriv — COMMENTED** [review]
PR description is too short. You can use this format:

```
# Description
This is a summary of the changes. This should describe why do we need this change.
Whys and Hows come here.

# Cards
* https://clickup.com/12345
* https://clickup.com/12346

```

**Review by sanjam-deriv — APPROVED** [review]

**Review by matin-deriv — DISMISSED** [review]

**Review by amina-deriv — APPROVED** [review]

**Review by amina-deriv — APPROVED** [review]

**Pull request merged**
